sudo: required
services:
  - docker
before_install:
  - docker build -t mahakagarwal248/server -f DockerFile.dev .
script:
  - docker run mahakagarwal248/server npm test -- --coverage
after_success:
  #decrypt env variables
  - openssl enc -aes256 -d -in .enc cipher -out .env -k $SECRET_KEY
  #build production grade dockerfile
  - docker build -t mahakagarwal248/server .
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push mahakagarwal248/server